// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package schedule

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var _ protoreflect.List = (*_PlannedSemester_2_list)(nil)

type _PlannedSemester_2_list struct {
	list *[]string
}

func (x *_PlannedSemester_2_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_PlannedSemester_2_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_PlannedSemester_2_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_PlannedSemester_2_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_PlannedSemester_2_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message PlannedSemester at list field PlannedSubjects as it is not of Message kind"))
}

func (x *_PlannedSemester_2_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_PlannedSemester_2_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_PlannedSemester_2_list) IsValid() bool {
	return x.list != nil
}

var (
	md_PlannedSemester                 protoreflect.MessageDescriptor
	fd_PlannedSemester_semesterCode    protoreflect.FieldDescriptor
	fd_PlannedSemester_plannedSubjects protoreflect.FieldDescriptor
	fd_PlannedSemester_totalCredits    protoreflect.FieldDescriptor
	fd_PlannedSemester_totalHours      protoreflect.FieldDescriptor
	fd_PlannedSemester_status          protoreflect.FieldDescriptor
)

func init() {
	file_academictoken_schedule_planned_semester_proto_init()
	md_PlannedSemester = File_academictoken_schedule_planned_semester_proto.Messages().ByName("PlannedSemester")
	fd_PlannedSemester_semesterCode = md_PlannedSemester.Fields().ByName("semesterCode")
	fd_PlannedSemester_plannedSubjects = md_PlannedSemester.Fields().ByName("plannedSubjects")
	fd_PlannedSemester_totalCredits = md_PlannedSemester.Fields().ByName("totalCredits")
	fd_PlannedSemester_totalHours = md_PlannedSemester.Fields().ByName("totalHours")
	fd_PlannedSemester_status = md_PlannedSemester.Fields().ByName("status")
}

var _ protoreflect.Message = (*fastReflection_PlannedSemester)(nil)

type fastReflection_PlannedSemester PlannedSemester

func (x *PlannedSemester) ProtoReflect() protoreflect.Message {
	return (*fastReflection_PlannedSemester)(x)
}

func (x *PlannedSemester) slowProtoReflect() protoreflect.Message {
	mi := &file_academictoken_schedule_planned_semester_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_PlannedSemester_messageType fastReflection_PlannedSemester_messageType
var _ protoreflect.MessageType = fastReflection_PlannedSemester_messageType{}

type fastReflection_PlannedSemester_messageType struct{}

func (x fastReflection_PlannedSemester_messageType) Zero() protoreflect.Message {
	return (*fastReflection_PlannedSemester)(nil)
}
func (x fastReflection_PlannedSemester_messageType) New() protoreflect.Message {
	return new(fastReflection_PlannedSemester)
}
func (x fastReflection_PlannedSemester_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_PlannedSemester
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_PlannedSemester) Descriptor() protoreflect.MessageDescriptor {
	return md_PlannedSemester
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_PlannedSemester) Type() protoreflect.MessageType {
	return _fastReflection_PlannedSemester_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_PlannedSemester) New() protoreflect.Message {
	return new(fastReflection_PlannedSemester)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_PlannedSemester) Interface() protoreflect.ProtoMessage {
	return (*PlannedSemester)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_PlannedSemester) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.SemesterCode != "" {
		value := protoreflect.ValueOfString(x.SemesterCode)
		if !f(fd_PlannedSemester_semesterCode, value) {
			return
		}
	}
	if len(x.PlannedSubjects) != 0 {
		value := protoreflect.ValueOfList(&_PlannedSemester_2_list{list: &x.PlannedSubjects})
		if !f(fd_PlannedSemester_plannedSubjects, value) {
			return
		}
	}
	if x.TotalCredits != "" {
		value := protoreflect.ValueOfString(x.TotalCredits)
		if !f(fd_PlannedSemester_totalCredits, value) {
			return
		}
	}
	if x.TotalHours != "" {
		value := protoreflect.ValueOfString(x.TotalHours)
		if !f(fd_PlannedSemester_totalHours, value) {
			return
		}
	}
	if x.Status != "" {
		value := protoreflect.ValueOfString(x.Status)
		if !f(fd_PlannedSemester_status, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_PlannedSemester) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "academictoken.schedule.PlannedSemester.semesterCode":
		return x.SemesterCode != ""
	case "academictoken.schedule.PlannedSemester.plannedSubjects":
		return len(x.PlannedSubjects) != 0
	case "academictoken.schedule.PlannedSemester.totalCredits":
		return x.TotalCredits != ""
	case "academictoken.schedule.PlannedSemester.totalHours":
		return x.TotalHours != ""
	case "academictoken.schedule.PlannedSemester.status":
		return x.Status != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.schedule.PlannedSemester"))
		}
		panic(fmt.Errorf("message academictoken.schedule.PlannedSemester does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PlannedSemester) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "academictoken.schedule.PlannedSemester.semesterCode":
		x.SemesterCode = ""
	case "academictoken.schedule.PlannedSemester.plannedSubjects":
		x.PlannedSubjects = nil
	case "academictoken.schedule.PlannedSemester.totalCredits":
		x.TotalCredits = ""
	case "academictoken.schedule.PlannedSemester.totalHours":
		x.TotalHours = ""
	case "academictoken.schedule.PlannedSemester.status":
		x.Status = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.schedule.PlannedSemester"))
		}
		panic(fmt.Errorf("message academictoken.schedule.PlannedSemester does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_PlannedSemester) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "academictoken.schedule.PlannedSemester.semesterCode":
		value := x.SemesterCode
		return protoreflect.ValueOfString(value)
	case "academictoken.schedule.PlannedSemester.plannedSubjects":
		if len(x.PlannedSubjects) == 0 {
			return protoreflect.ValueOfList(&_PlannedSemester_2_list{})
		}
		listValue := &_PlannedSemester_2_list{list: &x.PlannedSubjects}
		return protoreflect.ValueOfList(listValue)
	case "academictoken.schedule.PlannedSemester.totalCredits":
		value := x.TotalCredits
		return protoreflect.ValueOfString(value)
	case "academictoken.schedule.PlannedSemester.totalHours":
		value := x.TotalHours
		return protoreflect.ValueOfString(value)
	case "academictoken.schedule.PlannedSemester.status":
		value := x.Status
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.schedule.PlannedSemester"))
		}
		panic(fmt.Errorf("message academictoken.schedule.PlannedSemester does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PlannedSemester) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "academictoken.schedule.PlannedSemester.semesterCode":
		x.SemesterCode = value.Interface().(string)
	case "academictoken.schedule.PlannedSemester.plannedSubjects":
		lv := value.List()
		clv := lv.(*_PlannedSemester_2_list)
		x.PlannedSubjects = *clv.list
	case "academictoken.schedule.PlannedSemester.totalCredits":
		x.TotalCredits = value.Interface().(string)
	case "academictoken.schedule.PlannedSemester.totalHours":
		x.TotalHours = value.Interface().(string)
	case "academictoken.schedule.PlannedSemester.status":
		x.Status = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.schedule.PlannedSemester"))
		}
		panic(fmt.Errorf("message academictoken.schedule.PlannedSemester does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PlannedSemester) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "academictoken.schedule.PlannedSemester.plannedSubjects":
		if x.PlannedSubjects == nil {
			x.PlannedSubjects = []string{}
		}
		value := &_PlannedSemester_2_list{list: &x.PlannedSubjects}
		return protoreflect.ValueOfList(value)
	case "academictoken.schedule.PlannedSemester.semesterCode":
		panic(fmt.Errorf("field semesterCode of message academictoken.schedule.PlannedSemester is not mutable"))
	case "academictoken.schedule.PlannedSemester.totalCredits":
		panic(fmt.Errorf("field totalCredits of message academictoken.schedule.PlannedSemester is not mutable"))
	case "academictoken.schedule.PlannedSemester.totalHours":
		panic(fmt.Errorf("field totalHours of message academictoken.schedule.PlannedSemester is not mutable"))
	case "academictoken.schedule.PlannedSemester.status":
		panic(fmt.Errorf("field status of message academictoken.schedule.PlannedSemester is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.schedule.PlannedSemester"))
		}
		panic(fmt.Errorf("message academictoken.schedule.PlannedSemester does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_PlannedSemester) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "academictoken.schedule.PlannedSemester.semesterCode":
		return protoreflect.ValueOfString("")
	case "academictoken.schedule.PlannedSemester.plannedSubjects":
		list := []string{}
		return protoreflect.ValueOfList(&_PlannedSemester_2_list{list: &list})
	case "academictoken.schedule.PlannedSemester.totalCredits":
		return protoreflect.ValueOfString("")
	case "academictoken.schedule.PlannedSemester.totalHours":
		return protoreflect.ValueOfString("")
	case "academictoken.schedule.PlannedSemester.status":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.schedule.PlannedSemester"))
		}
		panic(fmt.Errorf("message academictoken.schedule.PlannedSemester does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_PlannedSemester) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in academictoken.schedule.PlannedSemester", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_PlannedSemester) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PlannedSemester) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_PlannedSemester) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_PlannedSemester) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*PlannedSemester)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.SemesterCode)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if len(x.PlannedSubjects) > 0 {
			for _, s := range x.PlannedSubjects {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		l = len(x.TotalCredits)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.TotalHours)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Status)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*PlannedSemester)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Status) > 0 {
			i -= len(x.Status)
			copy(dAtA[i:], x.Status)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Status)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.TotalHours) > 0 {
			i -= len(x.TotalHours)
			copy(dAtA[i:], x.TotalHours)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.TotalHours)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.TotalCredits) > 0 {
			i -= len(x.TotalCredits)
			copy(dAtA[i:], x.TotalCredits)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.TotalCredits)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.PlannedSubjects) > 0 {
			for iNdEx := len(x.PlannedSubjects) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.PlannedSubjects[iNdEx])
				copy(dAtA[i:], x.PlannedSubjects[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.PlannedSubjects[iNdEx])))
				i--
				dAtA[i] = 0x12
			}
		}
		if len(x.SemesterCode) > 0 {
			i -= len(x.SemesterCode)
			copy(dAtA[i:], x.SemesterCode)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.SemesterCode)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*PlannedSemester)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: PlannedSemester: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: PlannedSemester: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SemesterCode", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.SemesterCode = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PlannedSubjects", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.PlannedSubjects = append(x.PlannedSubjects, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TotalCredits", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.TotalCredits = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TotalHours", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.TotalHours = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Status = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: academictoken/schedule/planned_semester.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlannedSemester struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SemesterCode    string   `protobuf:"bytes,1,opt,name=semesterCode,proto3" json:"semesterCode,omitempty"`
	PlannedSubjects []string `protobuf:"bytes,2,rep,name=plannedSubjects,proto3" json:"plannedSubjects,omitempty"`
	TotalCredits    string   `protobuf:"bytes,3,opt,name=totalCredits,proto3" json:"totalCredits,omitempty"`
	TotalHours      string   `protobuf:"bytes,4,opt,name=totalHours,proto3" json:"totalHours,omitempty"`
	Status          string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *PlannedSemester) Reset() {
	*x = PlannedSemester{}
	if protoimpl.UnsafeEnabled {
		mi := &file_academictoken_schedule_planned_semester_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlannedSemester) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlannedSemester) ProtoMessage() {}

// Deprecated: Use PlannedSemester.ProtoReflect.Descriptor instead.
func (*PlannedSemester) Descriptor() ([]byte, []int) {
	return file_academictoken_schedule_planned_semester_proto_rawDescGZIP(), []int{0}
}

func (x *PlannedSemester) GetSemesterCode() string {
	if x != nil {
		return x.SemesterCode
	}
	return ""
}

func (x *PlannedSemester) GetPlannedSubjects() []string {
	if x != nil {
		return x.PlannedSubjects
	}
	return nil
}

func (x *PlannedSemester) GetTotalCredits() string {
	if x != nil {
		return x.TotalCredits
	}
	return ""
}

func (x *PlannedSemester) GetTotalHours() string {
	if x != nil {
		return x.TotalHours
	}
	return ""
}

func (x *PlannedSemester) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_academictoken_schedule_planned_semester_proto protoreflect.FileDescriptor

var file_academictoken_schedule_planned_semester_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f,
	0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x64,
	0x5f, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x16, 0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x73,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x22, 0xbb, 0x01, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x6e,
	0x6e, 0x65, 0x64, 0x53, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x73,
	0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x28, 0x0a, 0x0f, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x65,
	0x64, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0xd5, 0x01, 0x0a, 0x1a, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x63,
	0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x73, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x42, 0x14, 0x50, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x53, 0x65, 0x6d,
	0x65, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x28, 0x61, 0x63,
	0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x73, 0x63,
	0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0xa2, 0x02, 0x03, 0x41, 0x53, 0x58, 0xaa, 0x02, 0x16, 0x41,
	0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0xca, 0x02, 0x16, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5c, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0xe2, 0x02,
	0x22, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5c, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x17, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x3a, 0x3a, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_academictoken_schedule_planned_semester_proto_rawDescOnce sync.Once
	file_academictoken_schedule_planned_semester_proto_rawDescData = file_academictoken_schedule_planned_semester_proto_rawDesc
)

func file_academictoken_schedule_planned_semester_proto_rawDescGZIP() []byte {
	file_academictoken_schedule_planned_semester_proto_rawDescOnce.Do(func() {
		file_academictoken_schedule_planned_semester_proto_rawDescData = protoimpl.X.CompressGZIP(file_academictoken_schedule_planned_semester_proto_rawDescData)
	})
	return file_academictoken_schedule_planned_semester_proto_rawDescData
}

var file_academictoken_schedule_planned_semester_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_academictoken_schedule_planned_semester_proto_goTypes = []interface{}{
	(*PlannedSemester)(nil), // 0: academictoken.schedule.PlannedSemester
}
var file_academictoken_schedule_planned_semester_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_academictoken_schedule_planned_semester_proto_init() }
func file_academictoken_schedule_planned_semester_proto_init() {
	if File_academictoken_schedule_planned_semester_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_academictoken_schedule_planned_semester_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlannedSemester); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_academictoken_schedule_planned_semester_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_academictoken_schedule_planned_semester_proto_goTypes,
		DependencyIndexes: file_academictoken_schedule_planned_semester_proto_depIdxs,
		MessageInfos:      file_academictoken_schedule_planned_semester_proto_msgTypes,
	}.Build()
	File_academictoken_schedule_planned_semester_proto = out.File
	file_academictoken_schedule_planned_semester_proto_rawDesc = nil
	file_academictoken_schedule_planned_semester_proto_goTypes = nil
	file_academictoken_schedule_planned_semester_proto_depIdxs = nil
}
