// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package student

import (
	binary "encoding/binary"
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	math "math"
	reflect "reflect"
	sort "sort"
	sync "sync"
)

var _ protoreflect.Map = (*_AcademicProgress_7_map)(nil)

type _AcademicProgress_7_map struct {
	m *map[string]uint64
}

func (x *_AcademicProgress_7_map) Len() int {
	if x.m == nil {
		return 0
	}
	return len(*x.m)
}

func (x *_AcademicProgress_7_map) Range(f func(protoreflect.MapKey, protoreflect.Value) bool) {
	if x.m == nil {
		return
	}
	for k, v := range *x.m {
		mapKey := (protoreflect.MapKey)(protoreflect.ValueOfString(k))
		mapValue := protoreflect.ValueOfUint64(v)
		if !f(mapKey, mapValue) {
			break
		}
	}
}

func (x *_AcademicProgress_7_map) Has(key protoreflect.MapKey) bool {
	if x.m == nil {
		return false
	}
	keyUnwrapped := key.String()
	concreteValue := keyUnwrapped
	_, ok := (*x.m)[concreteValue]
	return ok
}

func (x *_AcademicProgress_7_map) Clear(key protoreflect.MapKey) {
	if x.m == nil {
		return
	}
	keyUnwrapped := key.String()
	concreteKey := keyUnwrapped
	delete(*x.m, concreteKey)
}

func (x *_AcademicProgress_7_map) Get(key protoreflect.MapKey) protoreflect.Value {
	if x.m == nil {
		return protoreflect.Value{}
	}
	keyUnwrapped := key.String()
	concreteKey := keyUnwrapped
	v, ok := (*x.m)[concreteKey]
	if !ok {
		return protoreflect.Value{}
	}
	return protoreflect.ValueOfUint64(v)
}

func (x *_AcademicProgress_7_map) Set(key protoreflect.MapKey, value protoreflect.Value) {
	if !key.IsValid() || !value.IsValid() {
		panic("invalid key or value provided")
	}
	keyUnwrapped := key.String()
	concreteKey := keyUnwrapped
	valueUnwrapped := value.Uint()
	concreteValue := valueUnwrapped
	(*x.m)[concreteKey] = concreteValue
}

func (x *_AcademicProgress_7_map) Mutable(key protoreflect.MapKey) protoreflect.Value {
	panic("should not call Mutable on protoreflect.Map whose value is not of type protoreflect.Message")
}

func (x *_AcademicProgress_7_map) NewValue() protoreflect.Value {
	v := uint64(0)
	return protoreflect.ValueOfUint64(v)
}

func (x *_AcademicProgress_7_map) IsValid() bool {
	return x.m != nil
}

var (
	md_AcademicProgress                            protoreflect.MessageDescriptor
	fd_AcademicProgress_requiredCreditsCompleted   protoreflect.FieldDescriptor
	fd_AcademicProgress_electiveCreditsCompleted   protoreflect.FieldDescriptor
	fd_AcademicProgress_requiredSubjectsPercentage protoreflect.FieldDescriptor
	fd_AcademicProgress_currentSemester            protoreflect.FieldDescriptor
	fd_AcademicProgress_currentYear                protoreflect.FieldDescriptor
	fd_AcademicProgress_enrollmentYears            protoreflect.FieldDescriptor
	fd_AcademicProgress_electivesByAreaCompleted   protoreflect.FieldDescriptor
)

func init() {
	file_academictoken_student_academic_progress_proto_init()
	md_AcademicProgress = File_academictoken_student_academic_progress_proto.Messages().ByName("AcademicProgress")
	fd_AcademicProgress_requiredCreditsCompleted = md_AcademicProgress.Fields().ByName("requiredCreditsCompleted")
	fd_AcademicProgress_electiveCreditsCompleted = md_AcademicProgress.Fields().ByName("electiveCreditsCompleted")
	fd_AcademicProgress_requiredSubjectsPercentage = md_AcademicProgress.Fields().ByName("requiredSubjectsPercentage")
	fd_AcademicProgress_currentSemester = md_AcademicProgress.Fields().ByName("currentSemester")
	fd_AcademicProgress_currentYear = md_AcademicProgress.Fields().ByName("currentYear")
	fd_AcademicProgress_enrollmentYears = md_AcademicProgress.Fields().ByName("enrollmentYears")
	fd_AcademicProgress_electivesByAreaCompleted = md_AcademicProgress.Fields().ByName("electivesByAreaCompleted")
}

var _ protoreflect.Message = (*fastReflection_AcademicProgress)(nil)

type fastReflection_AcademicProgress AcademicProgress

func (x *AcademicProgress) ProtoReflect() protoreflect.Message {
	return (*fastReflection_AcademicProgress)(x)
}

func (x *AcademicProgress) slowProtoReflect() protoreflect.Message {
	mi := &file_academictoken_student_academic_progress_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_AcademicProgress_messageType fastReflection_AcademicProgress_messageType
var _ protoreflect.MessageType = fastReflection_AcademicProgress_messageType{}

type fastReflection_AcademicProgress_messageType struct{}

func (x fastReflection_AcademicProgress_messageType) Zero() protoreflect.Message {
	return (*fastReflection_AcademicProgress)(nil)
}
func (x fastReflection_AcademicProgress_messageType) New() protoreflect.Message {
	return new(fastReflection_AcademicProgress)
}
func (x fastReflection_AcademicProgress_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_AcademicProgress
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_AcademicProgress) Descriptor() protoreflect.MessageDescriptor {
	return md_AcademicProgress
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_AcademicProgress) Type() protoreflect.MessageType {
	return _fastReflection_AcademicProgress_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_AcademicProgress) New() protoreflect.Message {
	return new(fastReflection_AcademicProgress)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_AcademicProgress) Interface() protoreflect.ProtoMessage {
	return (*AcademicProgress)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_AcademicProgress) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.RequiredCreditsCompleted != uint64(0) {
		value := protoreflect.ValueOfUint64(x.RequiredCreditsCompleted)
		if !f(fd_AcademicProgress_requiredCreditsCompleted, value) {
			return
		}
	}
	if x.ElectiveCreditsCompleted != uint64(0) {
		value := protoreflect.ValueOfUint64(x.ElectiveCreditsCompleted)
		if !f(fd_AcademicProgress_electiveCreditsCompleted, value) {
			return
		}
	}
	if x.RequiredSubjectsPercentage != float32(0) || math.Signbit(float64(x.RequiredSubjectsPercentage)) {
		value := protoreflect.ValueOfFloat32(x.RequiredSubjectsPercentage)
		if !f(fd_AcademicProgress_requiredSubjectsPercentage, value) {
			return
		}
	}
	if x.CurrentSemester != uint64(0) {
		value := protoreflect.ValueOfUint64(x.CurrentSemester)
		if !f(fd_AcademicProgress_currentSemester, value) {
			return
		}
	}
	if x.CurrentYear != uint64(0) {
		value := protoreflect.ValueOfUint64(x.CurrentYear)
		if !f(fd_AcademicProgress_currentYear, value) {
			return
		}
	}
	if x.EnrollmentYears != float32(0) || math.Signbit(float64(x.EnrollmentYears)) {
		value := protoreflect.ValueOfFloat32(x.EnrollmentYears)
		if !f(fd_AcademicProgress_enrollmentYears, value) {
			return
		}
	}
	if len(x.ElectivesByAreaCompleted) != 0 {
		value := protoreflect.ValueOfMap(&_AcademicProgress_7_map{m: &x.ElectivesByAreaCompleted})
		if !f(fd_AcademicProgress_electivesByAreaCompleted, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_AcademicProgress) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "academictoken.student.AcademicProgress.requiredCreditsCompleted":
		return x.RequiredCreditsCompleted != uint64(0)
	case "academictoken.student.AcademicProgress.electiveCreditsCompleted":
		return x.ElectiveCreditsCompleted != uint64(0)
	case "academictoken.student.AcademicProgress.requiredSubjectsPercentage":
		return x.RequiredSubjectsPercentage != float32(0) || math.Signbit(float64(x.RequiredSubjectsPercentage))
	case "academictoken.student.AcademicProgress.currentSemester":
		return x.CurrentSemester != uint64(0)
	case "academictoken.student.AcademicProgress.currentYear":
		return x.CurrentYear != uint64(0)
	case "academictoken.student.AcademicProgress.enrollmentYears":
		return x.EnrollmentYears != float32(0) || math.Signbit(float64(x.EnrollmentYears))
	case "academictoken.student.AcademicProgress.electivesByAreaCompleted":
		return len(x.ElectivesByAreaCompleted) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.student.AcademicProgress"))
		}
		panic(fmt.Errorf("message academictoken.student.AcademicProgress does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AcademicProgress) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "academictoken.student.AcademicProgress.requiredCreditsCompleted":
		x.RequiredCreditsCompleted = uint64(0)
	case "academictoken.student.AcademicProgress.electiveCreditsCompleted":
		x.ElectiveCreditsCompleted = uint64(0)
	case "academictoken.student.AcademicProgress.requiredSubjectsPercentage":
		x.RequiredSubjectsPercentage = float32(0)
	case "academictoken.student.AcademicProgress.currentSemester":
		x.CurrentSemester = uint64(0)
	case "academictoken.student.AcademicProgress.currentYear":
		x.CurrentYear = uint64(0)
	case "academictoken.student.AcademicProgress.enrollmentYears":
		x.EnrollmentYears = float32(0)
	case "academictoken.student.AcademicProgress.electivesByAreaCompleted":
		x.ElectivesByAreaCompleted = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.student.AcademicProgress"))
		}
		panic(fmt.Errorf("message academictoken.student.AcademicProgress does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_AcademicProgress) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "academictoken.student.AcademicProgress.requiredCreditsCompleted":
		value := x.RequiredCreditsCompleted
		return protoreflect.ValueOfUint64(value)
	case "academictoken.student.AcademicProgress.electiveCreditsCompleted":
		value := x.ElectiveCreditsCompleted
		return protoreflect.ValueOfUint64(value)
	case "academictoken.student.AcademicProgress.requiredSubjectsPercentage":
		value := x.RequiredSubjectsPercentage
		return protoreflect.ValueOfFloat32(value)
	case "academictoken.student.AcademicProgress.currentSemester":
		value := x.CurrentSemester
		return protoreflect.ValueOfUint64(value)
	case "academictoken.student.AcademicProgress.currentYear":
		value := x.CurrentYear
		return protoreflect.ValueOfUint64(value)
	case "academictoken.student.AcademicProgress.enrollmentYears":
		value := x.EnrollmentYears
		return protoreflect.ValueOfFloat32(value)
	case "academictoken.student.AcademicProgress.electivesByAreaCompleted":
		if len(x.ElectivesByAreaCompleted) == 0 {
			return protoreflect.ValueOfMap(&_AcademicProgress_7_map{})
		}
		mapValue := &_AcademicProgress_7_map{m: &x.ElectivesByAreaCompleted}
		return protoreflect.ValueOfMap(mapValue)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.student.AcademicProgress"))
		}
		panic(fmt.Errorf("message academictoken.student.AcademicProgress does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AcademicProgress) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "academictoken.student.AcademicProgress.requiredCreditsCompleted":
		x.RequiredCreditsCompleted = value.Uint()
	case "academictoken.student.AcademicProgress.electiveCreditsCompleted":
		x.ElectiveCreditsCompleted = value.Uint()
	case "academictoken.student.AcademicProgress.requiredSubjectsPercentage":
		x.RequiredSubjectsPercentage = float32(value.Float())
	case "academictoken.student.AcademicProgress.currentSemester":
		x.CurrentSemester = value.Uint()
	case "academictoken.student.AcademicProgress.currentYear":
		x.CurrentYear = value.Uint()
	case "academictoken.student.AcademicProgress.enrollmentYears":
		x.EnrollmentYears = float32(value.Float())
	case "academictoken.student.AcademicProgress.electivesByAreaCompleted":
		mv := value.Map()
		cmv := mv.(*_AcademicProgress_7_map)
		x.ElectivesByAreaCompleted = *cmv.m
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.student.AcademicProgress"))
		}
		panic(fmt.Errorf("message academictoken.student.AcademicProgress does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AcademicProgress) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "academictoken.student.AcademicProgress.electivesByAreaCompleted":
		if x.ElectivesByAreaCompleted == nil {
			x.ElectivesByAreaCompleted = make(map[string]uint64)
		}
		value := &_AcademicProgress_7_map{m: &x.ElectivesByAreaCompleted}
		return protoreflect.ValueOfMap(value)
	case "academictoken.student.AcademicProgress.requiredCreditsCompleted":
		panic(fmt.Errorf("field requiredCreditsCompleted of message academictoken.student.AcademicProgress is not mutable"))
	case "academictoken.student.AcademicProgress.electiveCreditsCompleted":
		panic(fmt.Errorf("field electiveCreditsCompleted of message academictoken.student.AcademicProgress is not mutable"))
	case "academictoken.student.AcademicProgress.requiredSubjectsPercentage":
		panic(fmt.Errorf("field requiredSubjectsPercentage of message academictoken.student.AcademicProgress is not mutable"))
	case "academictoken.student.AcademicProgress.currentSemester":
		panic(fmt.Errorf("field currentSemester of message academictoken.student.AcademicProgress is not mutable"))
	case "academictoken.student.AcademicProgress.currentYear":
		panic(fmt.Errorf("field currentYear of message academictoken.student.AcademicProgress is not mutable"))
	case "academictoken.student.AcademicProgress.enrollmentYears":
		panic(fmt.Errorf("field enrollmentYears of message academictoken.student.AcademicProgress is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.student.AcademicProgress"))
		}
		panic(fmt.Errorf("message academictoken.student.AcademicProgress does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_AcademicProgress) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "academictoken.student.AcademicProgress.requiredCreditsCompleted":
		return protoreflect.ValueOfUint64(uint64(0))
	case "academictoken.student.AcademicProgress.electiveCreditsCompleted":
		return protoreflect.ValueOfUint64(uint64(0))
	case "academictoken.student.AcademicProgress.requiredSubjectsPercentage":
		return protoreflect.ValueOfFloat32(float32(0))
	case "academictoken.student.AcademicProgress.currentSemester":
		return protoreflect.ValueOfUint64(uint64(0))
	case "academictoken.student.AcademicProgress.currentYear":
		return protoreflect.ValueOfUint64(uint64(0))
	case "academictoken.student.AcademicProgress.enrollmentYears":
		return protoreflect.ValueOfFloat32(float32(0))
	case "academictoken.student.AcademicProgress.electivesByAreaCompleted":
		m := make(map[string]uint64)
		return protoreflect.ValueOfMap(&_AcademicProgress_7_map{m: &m})
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: academictoken.student.AcademicProgress"))
		}
		panic(fmt.Errorf("message academictoken.student.AcademicProgress does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_AcademicProgress) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in academictoken.student.AcademicProgress", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_AcademicProgress) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AcademicProgress) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_AcademicProgress) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_AcademicProgress) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*AcademicProgress)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.RequiredCreditsCompleted != 0 {
			n += 1 + runtime.Sov(uint64(x.RequiredCreditsCompleted))
		}
		if x.ElectiveCreditsCompleted != 0 {
			n += 1 + runtime.Sov(uint64(x.ElectiveCreditsCompleted))
		}
		if x.RequiredSubjectsPercentage != 0 || math.Signbit(float64(x.RequiredSubjectsPercentage)) {
			n += 5
		}
		if x.CurrentSemester != 0 {
			n += 1 + runtime.Sov(uint64(x.CurrentSemester))
		}
		if x.CurrentYear != 0 {
			n += 1 + runtime.Sov(uint64(x.CurrentYear))
		}
		if x.EnrollmentYears != 0 || math.Signbit(float64(x.EnrollmentYears)) {
			n += 5
		}
		if len(x.ElectivesByAreaCompleted) > 0 {
			SiZeMaP := func(k string, v uint64) {
				mapEntrySize := 1 + len(k) + runtime.Sov(uint64(len(k))) + 1 + runtime.Sov(uint64(v))
				n += mapEntrySize + 1 + runtime.Sov(uint64(mapEntrySize))
			}
			if options.Deterministic {
				sortme := make([]string, 0, len(x.ElectivesByAreaCompleted))
				for k := range x.ElectivesByAreaCompleted {
					sortme = append(sortme, k)
				}
				sort.Strings(sortme)
				for _, k := range sortme {
					v := x.ElectivesByAreaCompleted[k]
					SiZeMaP(k, v)
				}
			} else {
				for k, v := range x.ElectivesByAreaCompleted {
					SiZeMaP(k, v)
				}
			}
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*AcademicProgress)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.ElectivesByAreaCompleted) > 0 {
			MaRsHaLmAp := func(k string, v uint64) (protoiface.MarshalOutput, error) {
				baseI := i
				i = runtime.EncodeVarint(dAtA, i, uint64(v))
				i--
				dAtA[i] = 0x10
				i -= len(k)
				copy(dAtA[i:], k)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(k)))
				i--
				dAtA[i] = 0xa
				i = runtime.EncodeVarint(dAtA, i, uint64(baseI-i))
				i--
				dAtA[i] = 0x3a
				return protoiface.MarshalOutput{}, nil
			}
			if options.Deterministic {
				keysForElectivesByAreaCompleted := make([]string, 0, len(x.ElectivesByAreaCompleted))
				for k := range x.ElectivesByAreaCompleted {
					keysForElectivesByAreaCompleted = append(keysForElectivesByAreaCompleted, string(k))
				}
				sort.Slice(keysForElectivesByAreaCompleted, func(i, j int) bool {
					return keysForElectivesByAreaCompleted[i] < keysForElectivesByAreaCompleted[j]
				})
				for iNdEx := len(keysForElectivesByAreaCompleted) - 1; iNdEx >= 0; iNdEx-- {
					v := x.ElectivesByAreaCompleted[string(keysForElectivesByAreaCompleted[iNdEx])]
					out, err := MaRsHaLmAp(keysForElectivesByAreaCompleted[iNdEx], v)
					if err != nil {
						return out, err
					}
				}
			} else {
				for k := range x.ElectivesByAreaCompleted {
					v := x.ElectivesByAreaCompleted[k]
					out, err := MaRsHaLmAp(k, v)
					if err != nil {
						return out, err
					}
				}
			}
		}
		if x.EnrollmentYears != 0 || math.Signbit(float64(x.EnrollmentYears)) {
			i -= 4
			binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(x.EnrollmentYears))))
			i--
			dAtA[i] = 0x35
		}
		if x.CurrentYear != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.CurrentYear))
			i--
			dAtA[i] = 0x28
		}
		if x.CurrentSemester != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.CurrentSemester))
			i--
			dAtA[i] = 0x20
		}
		if x.RequiredSubjectsPercentage != 0 || math.Signbit(float64(x.RequiredSubjectsPercentage)) {
			i -= 4
			binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(x.RequiredSubjectsPercentage))))
			i--
			dAtA[i] = 0x1d
		}
		if x.ElectiveCreditsCompleted != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.ElectiveCreditsCompleted))
			i--
			dAtA[i] = 0x10
		}
		if x.RequiredCreditsCompleted != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.RequiredCreditsCompleted))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*AcademicProgress)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: AcademicProgress: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: AcademicProgress: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field RequiredCreditsCompleted", wireType)
				}
				x.RequiredCreditsCompleted = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.RequiredCreditsCompleted |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ElectiveCreditsCompleted", wireType)
				}
				x.ElectiveCreditsCompleted = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.ElectiveCreditsCompleted |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 3:
				if wireType != 5 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field RequiredSubjectsPercentage", wireType)
				}
				var v uint32
				if (iNdEx + 4) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				v = uint32(binary.LittleEndian.Uint32(dAtA[iNdEx:]))
				iNdEx += 4
				x.RequiredSubjectsPercentage = float32(math.Float32frombits(v))
			case 4:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CurrentSemester", wireType)
				}
				x.CurrentSemester = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.CurrentSemester |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CurrentYear", wireType)
				}
				x.CurrentYear = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.CurrentYear |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 5 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field EnrollmentYears", wireType)
				}
				var v uint32
				if (iNdEx + 4) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				v = uint32(binary.LittleEndian.Uint32(dAtA[iNdEx:]))
				iNdEx += 4
				x.EnrollmentYears = float32(math.Float32frombits(v))
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ElectivesByAreaCompleted", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.ElectivesByAreaCompleted == nil {
					x.ElectivesByAreaCompleted = make(map[string]uint64)
				}
				var mapkey string
				var mapvalue uint64
				for iNdEx < postIndex {
					entryPreIndex := iNdEx
					var wire uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
						}
						if iNdEx >= l {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						wire |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					fieldNum := int32(wire >> 3)
					if fieldNum == 1 {
						var stringLenmapkey uint64
						for shift := uint(0); ; shift += 7 {
							if shift >= 64 {
								return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
							}
							if iNdEx >= l {
								return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
							}
							b := dAtA[iNdEx]
							iNdEx++
							stringLenmapkey |= uint64(b&0x7F) << shift
							if b < 0x80 {
								break
							}
						}
						intStringLenmapkey := int(stringLenmapkey)
						if intStringLenmapkey < 0 {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
						}
						postStringIndexmapkey := iNdEx + intStringLenmapkey
						if postStringIndexmapkey < 0 {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
						}
						if postStringIndexmapkey > l {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
						}
						mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
						iNdEx = postStringIndexmapkey
					} else if fieldNum == 2 {
						for shift := uint(0); ; shift += 7 {
							if shift >= 64 {
								return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
							}
							if iNdEx >= l {
								return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
							}
							b := dAtA[iNdEx]
							iNdEx++
							mapvalue |= uint64(b&0x7F) << shift
							if b < 0x80 {
								break
							}
						}
					} else {
						iNdEx = entryPreIndex
						skippy, err := runtime.Skip(dAtA[iNdEx:])
						if err != nil {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
						}
						if (skippy < 0) || (iNdEx+skippy) < 0 {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
						}
						if (iNdEx + skippy) > postIndex {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
						}
						iNdEx += skippy
					}
				}
				x.ElectivesByAreaCompleted[mapkey] = mapvalue
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: academictoken/student/academic_progress.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcademicProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequiredCreditsCompleted   uint64            `protobuf:"varint,1,opt,name=requiredCreditsCompleted,proto3" json:"requiredCreditsCompleted,omitempty"`
	ElectiveCreditsCompleted   uint64            `protobuf:"varint,2,opt,name=electiveCreditsCompleted,proto3" json:"electiveCreditsCompleted,omitempty"`
	RequiredSubjectsPercentage float32           `protobuf:"fixed32,3,opt,name=requiredSubjectsPercentage,proto3" json:"requiredSubjectsPercentage,omitempty"`
	CurrentSemester            uint64            `protobuf:"varint,4,opt,name=currentSemester,proto3" json:"currentSemester,omitempty"`
	CurrentYear                uint64            `protobuf:"varint,5,opt,name=currentYear,proto3" json:"currentYear,omitempty"`
	EnrollmentYears            float32           `protobuf:"fixed32,6,opt,name=enrollmentYears,proto3" json:"enrollmentYears,omitempty"`
	ElectivesByAreaCompleted   map[string]uint64 `protobuf:"bytes,7,rep,name=electivesByAreaCompleted,proto3" json:"electivesByAreaCompleted,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *AcademicProgress) Reset() {
	*x = AcademicProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_academictoken_student_academic_progress_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcademicProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcademicProgress) ProtoMessage() {}

// Deprecated: Use AcademicProgress.ProtoReflect.Descriptor instead.
func (*AcademicProgress) Descriptor() ([]byte, []int) {
	return file_academictoken_student_academic_progress_proto_rawDescGZIP(), []int{0}
}

func (x *AcademicProgress) GetRequiredCreditsCompleted() uint64 {
	if x != nil {
		return x.RequiredCreditsCompleted
	}
	return 0
}

func (x *AcademicProgress) GetElectiveCreditsCompleted() uint64 {
	if x != nil {
		return x.ElectiveCreditsCompleted
	}
	return 0
}

func (x *AcademicProgress) GetRequiredSubjectsPercentage() float32 {
	if x != nil {
		return x.RequiredSubjectsPercentage
	}
	return 0
}

func (x *AcademicProgress) GetCurrentSemester() uint64 {
	if x != nil {
		return x.CurrentSemester
	}
	return 0
}

func (x *AcademicProgress) GetCurrentYear() uint64 {
	if x != nil {
		return x.CurrentYear
	}
	return 0
}

func (x *AcademicProgress) GetEnrollmentYears() float32 {
	if x != nil {
		return x.EnrollmentYears
	}
	return 0
}

func (x *AcademicProgress) GetElectivesByAreaCompleted() map[string]uint64 {
	if x != nil {
		return x.ElectivesByAreaCompleted
	}
	return nil
}

var File_academictoken_student_academic_progress_proto protoreflect.FileDescriptor

var file_academictoken_student_academic_progress_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f,
	0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63,
	0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x15, 0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x73,
	0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x22, 0x91, 0x04, 0x0a, 0x10, 0x41, 0x63, 0x61, 0x64, 0x65,
	0x6d, 0x69, 0x63, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x3a, 0x0a, 0x18, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x18, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x3a, 0x0a, 0x18, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x18, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x12, 0x3e, 0x0a, 0x1a, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x53,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x1a, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x65,
	0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x12, 0x20, 0x0a,
	0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x59, 0x65, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x59, 0x65, 0x61, 0x72, 0x12,
	0x28, 0x0a, 0x0f, 0x65, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x59, 0x65, 0x61,
	0x72, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0f, 0x65, 0x6e, 0x72, 0x6f, 0x6c, 0x6c,
	0x6d, 0x65, 0x6e, 0x74, 0x59, 0x65, 0x61, 0x72, 0x73, 0x12, 0x81, 0x01, 0x0a, 0x18, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x42, 0x79, 0x41, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x45, 0x2e, 0x61,
	0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x73, 0x74, 0x75,
	0x64, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x42,
	0x79, 0x41, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x18, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x42, 0x79,
	0x41, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x1a, 0x4b, 0x0a,
	0x1d, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x42, 0x79, 0x41, 0x72, 0x65, 0x61,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0xd0, 0x01, 0x0a, 0x19, 0x63,
	0x6f, 0x6d, 0x2e, 0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x2e, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x42, 0x15, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d,
	0x69, 0x63, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x27, 0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x2f, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0xa2, 0x02, 0x03, 0x41, 0x53, 0x58,
	0xaa, 0x02, 0x15, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0xca, 0x02, 0x15, 0x41, 0x63, 0x61, 0x64, 0x65,
	0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5c, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74,
	0xe2, 0x02, 0x21, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x5c, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x16, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x3a, 0x3a, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_academictoken_student_academic_progress_proto_rawDescOnce sync.Once
	file_academictoken_student_academic_progress_proto_rawDescData = file_academictoken_student_academic_progress_proto_rawDesc
)

func file_academictoken_student_academic_progress_proto_rawDescGZIP() []byte {
	file_academictoken_student_academic_progress_proto_rawDescOnce.Do(func() {
		file_academictoken_student_academic_progress_proto_rawDescData = protoimpl.X.CompressGZIP(file_academictoken_student_academic_progress_proto_rawDescData)
	})
	return file_academictoken_student_academic_progress_proto_rawDescData
}

var file_academictoken_student_academic_progress_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_academictoken_student_academic_progress_proto_goTypes = []interface{}{
	(*AcademicProgress)(nil), // 0: academictoken.student.AcademicProgress
	nil,                      // 1: academictoken.student.AcademicProgress.ElectivesByAreaCompletedEntry
}
var file_academictoken_student_academic_progress_proto_depIdxs = []int32{
	1, // 0: academictoken.student.AcademicProgress.electivesByAreaCompleted:type_name -> academictoken.student.AcademicProgress.ElectivesByAreaCompletedEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_academictoken_student_academic_progress_proto_init() }
func file_academictoken_student_academic_progress_proto_init() {
	if File_academictoken_student_academic_progress_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_academictoken_student_academic_progress_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcademicProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_academictoken_student_academic_progress_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_academictoken_student_academic_progress_proto_goTypes,
		DependencyIndexes: file_academictoken_student_academic_progress_proto_depIdxs,
		MessageInfos:      file_academictoken_student_academic_progress_proto_msgTypes,
	}.Build()
	File_academictoken_student_academic_progress_proto = out.File
	file_academictoken_student_academic_progress_proto_rawDesc = nil
	file_academictoken_student_academic_progress_proto_goTypes = nil
	file_academictoken_student_academic_progress_proto_depIdxs = nil
}
