// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: academictoken/curriculum/query.proto

package curriculum

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName                  = "/academictoken.curriculum.Query/Params"
	Query_CurriculumTreeAll_FullMethodName       = "/academictoken.curriculum.Query/CurriculumTreeAll"
	Query_CurriculumTree_FullMethodName          = "/academictoken.curriculum.Query/CurriculumTree"
	Query_CurriculumTreesByCourse_FullMethodName = "/academictoken.curriculum.Query/CurriculumTreesByCourse"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of CurriculumTree items.
	CurriculumTreeAll(ctx context.Context, in *QueryAllCurriculumTreeRequest, opts ...grpc.CallOption) (*QueryAllCurriculumTreeResponse, error)
	// Queries a CurriculumTree by index.
	CurriculumTree(ctx context.Context, in *QueryGetCurriculumTreeRequest, opts ...grpc.CallOption) (*QueryGetCurriculumTreeResponse, error)
	// Queries curriculum trees by course
	CurriculumTreesByCourse(ctx context.Context, in *QueryCurriculumTreesByCourseRequest, opts ...grpc.CallOption) (*QueryCurriculumTreesByCourseResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CurriculumTreeAll(ctx context.Context, in *QueryAllCurriculumTreeRequest, opts ...grpc.CallOption) (*QueryAllCurriculumTreeResponse, error) {
	out := new(QueryAllCurriculumTreeResponse)
	err := c.cc.Invoke(ctx, Query_CurriculumTreeAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CurriculumTree(ctx context.Context, in *QueryGetCurriculumTreeRequest, opts ...grpc.CallOption) (*QueryGetCurriculumTreeResponse, error) {
	out := new(QueryGetCurriculumTreeResponse)
	err := c.cc.Invoke(ctx, Query_CurriculumTree_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CurriculumTreesByCourse(ctx context.Context, in *QueryCurriculumTreesByCourseRequest, opts ...grpc.CallOption) (*QueryCurriculumTreesByCourseResponse, error) {
	out := new(QueryCurriculumTreesByCourseResponse)
	err := c.cc.Invoke(ctx, Query_CurriculumTreesByCourse_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of CurriculumTree items.
	CurriculumTreeAll(context.Context, *QueryAllCurriculumTreeRequest) (*QueryAllCurriculumTreeResponse, error)
	// Queries a CurriculumTree by index.
	CurriculumTree(context.Context, *QueryGetCurriculumTreeRequest) (*QueryGetCurriculumTreeResponse, error)
	// Queries curriculum trees by course
	CurriculumTreesByCourse(context.Context, *QueryCurriculumTreesByCourseRequest) (*QueryCurriculumTreesByCourseResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) CurriculumTreeAll(context.Context, *QueryAllCurriculumTreeRequest) (*QueryAllCurriculumTreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurriculumTreeAll not implemented")
}
func (UnimplementedQueryServer) CurriculumTree(context.Context, *QueryGetCurriculumTreeRequest) (*QueryGetCurriculumTreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurriculumTree not implemented")
}
func (UnimplementedQueryServer) CurriculumTreesByCourse(context.Context, *QueryCurriculumTreesByCourseRequest) (*QueryCurriculumTreesByCourseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurriculumTreesByCourse not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CurriculumTreeAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllCurriculumTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CurriculumTreeAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_CurriculumTreeAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CurriculumTreeAll(ctx, req.(*QueryAllCurriculumTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CurriculumTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCurriculumTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CurriculumTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_CurriculumTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CurriculumTree(ctx, req.(*QueryGetCurriculumTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CurriculumTreesByCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCurriculumTreesByCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CurriculumTreesByCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_CurriculumTreesByCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CurriculumTreesByCourse(ctx, req.(*QueryCurriculumTreesByCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "academictoken.curriculum.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "CurriculumTreeAll",
			Handler:    _Query_CurriculumTreeAll_Handler,
		},
		{
			MethodName: "CurriculumTree",
			Handler:    _Query_CurriculumTree_Handler,
		},
		{
			MethodName: "CurriculumTreesByCourse",
			Handler:    _Query_CurriculumTreesByCourse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "academictoken/curriculum/query.proto",
}
