// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: academictoken/student/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	IpfsGateway                  string `protobuf:"bytes,1,opt,name=ipfs_gateway,json=ipfsGateway,proto3" json:"ipfs_gateway,omitempty" yaml:"ipfs_gateway"`
	IpfsEnabled                  bool   `protobuf:"varint,2,opt,name=ipfs_enabled,json=ipfsEnabled,proto3" json:"ipfs_enabled,omitempty" yaml:"ipfs_enabled"`
	Admin                        string `protobuf:"bytes,3,opt,name=admin,proto3" json:"admin,omitempty" yaml:"admin"`
	PrerequisitesContractAddr    string `protobuf:"bytes,4,opt,name=prerequisites_contract_addr,json=prerequisitesContractAddr,proto3" json:"prerequisites_contract_addr,omitempty" yaml:"prerequisites_contract_addr"`
	EquivalenceContractAddr      string `protobuf:"bytes,5,opt,name=equivalence_contract_addr,json=equivalenceContractAddr,proto3" json:"equivalence_contract_addr,omitempty" yaml:"equivalence_contract_addr"`
	AcademicProgressContractAddr string `protobuf:"bytes,6,opt,name=academic_progress_contract_addr,json=academicProgressContractAddr,proto3" json:"academic_progress_contract_addr,omitempty" yaml:"academic_progress_contract_addr"`
	DegreeContractAddr           string `protobuf:"bytes,7,opt,name=degree_contract_addr,json=degreeContractAddr,proto3" json:"degree_contract_addr,omitempty" yaml:"degree_contract_addr"`
	NftMintingContractAddr       string `protobuf:"bytes,8,opt,name=nft_minting_contract_addr,json=nftMintingContractAddr,proto3" json:"nft_minting_contract_addr,omitempty" yaml:"nft_minting_contract_addr"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_e856631a2f19ed9a, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetIpfsGateway() string {
	if m != nil {
		return m.IpfsGateway
	}
	return ""
}

func (m *Params) GetIpfsEnabled() bool {
	if m != nil {
		return m.IpfsEnabled
	}
	return false
}

func (m *Params) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *Params) GetPrerequisitesContractAddr() string {
	if m != nil {
		return m.PrerequisitesContractAddr
	}
	return ""
}

func (m *Params) GetEquivalenceContractAddr() string {
	if m != nil {
		return m.EquivalenceContractAddr
	}
	return ""
}

func (m *Params) GetAcademicProgressContractAddr() string {
	if m != nil {
		return m.AcademicProgressContractAddr
	}
	return ""
}

func (m *Params) GetDegreeContractAddr() string {
	if m != nil {
		return m.DegreeContractAddr
	}
	return ""
}

func (m *Params) GetNftMintingContractAddr() string {
	if m != nil {
		return m.NftMintingContractAddr
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "academictoken.student.Params")
}

func init() {
	proto.RegisterFile("academictoken/student/params.proto", fileDescriptor_e856631a2f19ed9a)
}

var fileDescriptor_e856631a2f19ed9a = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xb1, 0xae, 0xd3, 0x30,
	0x14, 0x86, 0x1b, 0xa0, 0xe5, 0x62, 0xee, 0x00, 0xe1, 0xc2, 0x4d, 0x6f, 0x21, 0xae, 0x2c, 0x54,
	0xaa, 0x0e, 0xcd, 0xc0, 0x80, 0xd4, 0x8d, 0x22, 0xc4, 0x84, 0x54, 0x32, 0xb2, 0x04, 0x37, 0x76,
	0x22, 0x8b, 0xc6, 0x4e, 0x1d, 0x17, 0xe8, 0x2b, 0x30, 0xf1, 0x08, 0x3c, 0x02, 0xcf, 0xc0, 0xc4,
	0xd8, 0x91, 0x29, 0x42, 0xed, 0x00, 0x73, 0x9e, 0x00, 0xd5, 0x4e, 0xab, 0x26, 0xd0, 0x2e, 0x95,
	0xcf, 0xf9, 0xff, 0xff, 0x7c, 0xb2, 0x9b, 0x03, 0x10, 0x0e, 0x31, 0xa1, 0x09, 0x0b, 0x95, 0x78,
	0x4f, 0xb9, 0x97, 0xa9, 0x05, 0xa1, 0x5c, 0x79, 0x29, 0x96, 0x38, 0xc9, 0x86, 0xa9, 0x14, 0x4a,
	0xd8, 0xf7, 0x2b, 0x9e, 0x61, 0xe9, 0xb9, 0xba, 0x8b, 0x13, 0xc6, 0x85, 0xa7, 0x7f, 0x8d, 0xf3,
	0xea, 0x22, 0x16, 0xb1, 0xd0, 0x47, 0x6f, 0x7b, 0x32, 0x5d, 0xf4, 0xbd, 0x09, 0x5a, 0x13, 0x3d,
	0xd0, 0x1e, 0x81, 0x73, 0x96, 0x46, 0x59, 0x10, 0x63, 0x45, 0x3f, 0xe2, 0xa5, 0x63, 0x75, 0xad,
	0xfe, 0xad, 0xf1, 0x65, 0x91, 0xc3, 0x7b, 0x4b, 0x9c, 0xcc, 0x46, 0xe8, 0x50, 0x45, 0xfe, 0xed,
	0x6d, 0xf9, 0xca, 0x54, 0xfb, 0x2c, 0xe5, 0x78, 0x3a, 0xa3, 0xc4, 0xb9, 0xd6, 0xb5, 0xfa, 0x67,
	0xff, 0x64, 0x4b, 0xb5, 0xcc, 0xbe, 0x34, 0x95, 0xdd, 0x03, 0x4d, 0x4c, 0x12, 0xc6, 0x9d, 0xeb,
	0x1a, 0x78, 0xa7, 0xc8, 0xe1, 0xb9, 0x09, 0xe9, 0x36, 0xf2, 0x8d, 0x6c, 0x47, 0xa0, 0x93, 0x4a,
	0x2a, 0xe9, 0x7c, 0xc1, 0x32, 0xa6, 0x68, 0x16, 0x84, 0x82, 0x2b, 0x89, 0x43, 0x15, 0x60, 0x42,
	0xa4, 0x73, 0x43, 0xa7, 0x7b, 0x45, 0x0e, 0x91, 0x49, 0x9f, 0x30, 0x23, 0xbf, 0x5d, 0x51, 0x5f,
	0x94, 0xe2, 0x73, 0x42, 0xa4, 0xfd, 0x0e, 0xb4, 0xb7, 0xc2, 0x07, 0x3c, 0xa3, 0x3c, 0xa4, 0x35,
	0x4a, 0x53, 0x53, 0x1e, 0x17, 0x39, 0xec, 0x1a, 0xca, 0x51, 0x2b, 0xf2, 0x2f, 0x0f, 0xb4, 0x0a,
	0x61, 0x0e, 0xe0, 0xee, 0x6f, 0x0b, 0x52, 0x29, 0x62, 0x49, 0xb3, 0xfa, 0x6d, 0x5a, 0x9a, 0x33,
	0x28, 0x72, 0xd8, 0x2b, 0xdf, 0xe2, 0x74, 0x00, 0xf9, 0x0f, 0x77, 0x8e, 0x49, 0x69, 0xa8, 0x20,
	0xdf, 0x80, 0x0b, 0x42, 0x63, 0x49, 0xeb, 0xf7, 0xb9, 0xa9, 0x39, 0xb0, 0xc8, 0x61, 0xc7, 0x70,
	0xfe, 0xe7, 0x42, 0xbe, 0x6d, 0xda, 0x95, 0x91, 0x01, 0x68, 0xf3, 0x48, 0x05, 0x09, 0xe3, 0x8a,
	0xf1, 0xb8, 0x36, 0xf7, 0xac, 0xfe, 0x4e, 0x47, 0xad, 0xc8, 0x7f, 0xc0, 0x23, 0xf5, 0xda, 0x48,
	0x87, 0x80, 0xd1, 0x93, 0x3f, 0x5f, 0xa1, 0xf5, 0xf9, 0xf7, 0xb7, 0x81, 0x5b, 0x5d, 0x84, 0x4f,
	0xfb, 0x55, 0x30, 0x5f, 0xee, 0xf8, 0xd9, 0x8f, 0xb5, 0x6b, 0xad, 0xd6, 0xae, 0xf5, 0x6b, 0xed,
	0x5a, 0x5f, 0x36, 0x6e, 0x63, 0xb5, 0x71, 0x1b, 0x3f, 0x37, 0x6e, 0xe3, 0xed, 0xa3, 0x63, 0x49,
	0xb5, 0x4c, 0x69, 0x36, 0x6d, 0xe9, 0x25, 0x78, 0xfa, 0x37, 0x00, 0x00, 0xff, 0xff, 0x36, 0x7d,
	0x6f, 0x4d, 0x6a, 0x03, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.IpfsGateway != that1.IpfsGateway {
		return false
	}
	if this.IpfsEnabled != that1.IpfsEnabled {
		return false
	}
	if this.Admin != that1.Admin {
		return false
	}
	if this.PrerequisitesContractAddr != that1.PrerequisitesContractAddr {
		return false
	}
	if this.EquivalenceContractAddr != that1.EquivalenceContractAddr {
		return false
	}
	if this.AcademicProgressContractAddr != that1.AcademicProgressContractAddr {
		return false
	}
	if this.DegreeContractAddr != that1.DegreeContractAddr {
		return false
	}
	if this.NftMintingContractAddr != that1.NftMintingContractAddr {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NftMintingContractAddr) > 0 {
		i -= len(m.NftMintingContractAddr)
		copy(dAtA[i:], m.NftMintingContractAddr)
		i = encodeVarintParams(dAtA, i, uint64(len(m.NftMintingContractAddr)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.DegreeContractAddr) > 0 {
		i -= len(m.DegreeContractAddr)
		copy(dAtA[i:], m.DegreeContractAddr)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DegreeContractAddr)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.AcademicProgressContractAddr) > 0 {
		i -= len(m.AcademicProgressContractAddr)
		copy(dAtA[i:], m.AcademicProgressContractAddr)
		i = encodeVarintParams(dAtA, i, uint64(len(m.AcademicProgressContractAddr)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.EquivalenceContractAddr) > 0 {
		i -= len(m.EquivalenceContractAddr)
		copy(dAtA[i:], m.EquivalenceContractAddr)
		i = encodeVarintParams(dAtA, i, uint64(len(m.EquivalenceContractAddr)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.PrerequisitesContractAddr) > 0 {
		i -= len(m.PrerequisitesContractAddr)
		copy(dAtA[i:], m.PrerequisitesContractAddr)
		i = encodeVarintParams(dAtA, i, uint64(len(m.PrerequisitesContractAddr)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0x1a
	}
	if m.IpfsEnabled {
		i--
		if m.IpfsEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.IpfsGateway) > 0 {
		i -= len(m.IpfsGateway)
		copy(dAtA[i:], m.IpfsGateway)
		i = encodeVarintParams(dAtA, i, uint64(len(m.IpfsGateway)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.IpfsGateway)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.IpfsEnabled {
		n += 2
	}
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.PrerequisitesContractAddr)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.EquivalenceContractAddr)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.AcademicProgressContractAddr)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.DegreeContractAddr)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.NftMintingContractAddr)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IpfsGateway", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IpfsGateway = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IpfsEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IpfsEnabled = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrerequisitesContractAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrerequisitesContractAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EquivalenceContractAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EquivalenceContractAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcademicProgressContractAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AcademicProgressContractAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DegreeContractAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DegreeContractAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftMintingContractAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftMintingContractAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
